// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfkTevEpgxr0xiGvpyb04xs219mfrgV9g',
    appId: '1:241933144493:web:5849597b385e932cbf5124',
    messagingSenderId: '241933144493',
    projectId: 'meme-creator-a0520',
    authDomain: 'meme-creator-a0520.firebaseapp.com',
    storageBucket: 'meme-creator-a0520.firebasestorage.app',
    measurementId: 'G-TMHQHSCMNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzaTe5LCXH_MtaXrpGb-wqG9zqrhEr1Z0',
    appId: '1:241933144493:android:d9cd216d5f076902bf5124',
    messagingSenderId: '241933144493',
    projectId: 'meme-creator-a0520',
    storageBucket: 'meme-creator-a0520.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV5PQlwnEN0mSbBhPB40GqNpPjRSnR4Qw',
    appId: '1:241933144493:ios:1dbd519423b8287bbf5124',
    messagingSenderId: '241933144493',
    projectId: 'meme-creator-a0520',
    storageBucket: 'meme-creator-a0520.firebasestorage.app',
    iosBundleId: 'com.example.memeCreator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV5PQlwnEN0mSbBhPB40GqNpPjRSnR4Qw',
    appId: '1:241933144493:ios:1dbd519423b8287bbf5124',
    messagingSenderId: '241933144493',
    projectId: 'meme-creator-a0520',
    storageBucket: 'meme-creator-a0520.firebasestorage.app',
    iosBundleId: 'com.example.memeCreator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfkTevEpgxr0xiGvpyb04xs219mfrgV9g',
    appId: '1:241933144493:web:2f987f133e280b18bf5124',
    messagingSenderId: '241933144493',
    projectId: 'meme-creator-a0520',
    authDomain: 'meme-creator-a0520.firebaseapp.com',
    storageBucket: 'meme-creator-a0520.firebasestorage.app',
    measurementId: 'G-XF9QR14K6G',
  );

}